tasks:
- init: >-
    export ZABBIX_SOURCE="$HOME/zabbix" &&
    git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 "$ZABBIX_SOURCE" &&
    cd "$ZABBIX_SOURCE" &&
    ./bootstrap.sh &&
    ./configure &&
    cd - &&
    bear make
image:
  file: .gitpod.Dockerfile
