tasks:
- init: >-
    export ZABBIX_SOURCE=zabbix &&
    git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 "$ZABBIX_SOURCE" &&
    "$ZABBIX_SOURCE/configure" &&
    make
image:
  file: .gitpod.Dockerfile
